### ISSUE TITLE
Перенести все это дело на hugo

### ISSUE THREAD

**Issue by umputun** [radio-t/pirates#1]
Задача перенести с octopress на hugo. 

- Желательно сохранить вид как есть, однако если будут мелкие различия с этим можно жить.
- Обязательно сохранить полностью идентичный RSS. В противном случае, все подкасты будут утянуты еще раз.
- Хорошо бы не трогать все посты (md файлы) при переносе. Однако, если без этого не обойтись, тогда должен быть какой скрипт для массовоого преобразования.
- Если какая-то неосновная функциональность вызывает слишком много хлопот, то можно это дело обсудить и (возможно) выбросить.

**Comment by taime** [comment]
Сделал PULL Request.

- md файлы пришлось изменить.
- disqus прикрутил успешно.

Есть некоторые моменты, которые сделаны не в точности, как было:

- картинка для RSS
- Кнопка для twitter-sharing и google sharing
- блок twitter справа
- в архиве год выводится каждый раз
- поиск по сайту Google не работает, как и прежде

**Comment by taime** [comment]
Все пофиксили.
