### ISSUE TITLE
Всякие ненужные npm библиотеки

### ISSUE THREAD

**Issue by umputun** [radio-t/pirates#11]
Они, как мне кажется, вообще тут не при деле и я не понимаю зачем это все надо (themes/pirates-radio-t)

Кроме того, там целый ряд секьюрити алертов

<img width="881" alt="gxq62-201810-20124310-ozshw" src="https://user-images.githubusercontent.com/535880/47258783-f874f500-d465-11e8-8b54-3c74576b891c.png">

**Comment by Piterden** [comment]
Обновите вебпак и предупреждения пропадут. Эти библиотеки нужны для разработки, однако сделано это все было кем-то криворуким и что с этим делать теперь - непонятно (

**Comment by umputun** [comment]
для разработки чего именно они тут, в статическим генераторе сайта, нужны?

**Comment by Piterden** [comment]
Ну вебпак это сборщик, он вкл.ючает компилятор кода из современного модернового JS в старый, тот что понимают браузеры, а также компиляторы CSS и другие утилиты для разработки. Ваш генератор статических сайтов - это не статический сайт. 

Кстати, ИМХО реакт - отстой. Взяли бы лучше [Vue](https://ru.vuejs.org/index.html) и [Nuxt](https://nuxtjs.org/guide/installation). Посмотрите на них...

**Comment by umputun** [comment]
ничего не понял. что этот сборщик и где запускает? Hugo строит из своих темплэйтов и, насколько я понимаю, никак вебпак не трогает
.

**Comment by Piterden** [comment]
```sh
$ npm start
```
запускает вебпак
```json
  "scripts": {
    "build:production": "rm -rf ../static/dist && webpack -p",
    "build": "webpack --progress --colors --watch",
    "start": "npm run build"
  },
```

**Comment by Piterden** [comment]
Слушайте, а почему вы собираете статический сайт? Ведь у вас радио, и следовательно, контент будет обновляться с некой периодичностью... Статический сайт - это сайт, требующий пересборки для изменения контента!

Пропробуйте посмотреть в сторону [getgrav.org](https://getgrav.org) - это система управления динамическим сайтом без БД

**Comment by umputun** [comment]
я не понял что не так с статической генерацией, но это не является предметом данного тикета. Тут простой вопрос и если есть PR предложить, решающий проблему то это будет более конструктивно чем советы как все переделать.

**Comment by Piterden** [comment]
А что вы ожидаете получить?

Со статической генерацией не то: вам надо будет перегенерировать сайт заново, при внесении каких-либо изменений, вместо того, чтобы просто зайти в админку и поменять то, что необходимо.

Напишите мне в телеграм, если вам интересно моё участие. Обсудим детали там, чтобы здесь не засорять.

**Comment by umputun** [comment]
я знаю что такое статическая генерация и этот конкретный сайт на ней живёт лет 8. никакого интереса все менять непонятно зачем,у меня нет. однако эта генерация совершенно точно никакого npm не запускает. в этом можно легко убедится посмотрев на Dockerfile и обнаружить, что никакого npm там не устанавливается.

добиться я хочу избавления от этих элементов если они, как я подозреваю, тут случайно. если они зачем-то нужны, хотя я не понимаю зачем, то тогда обновить версии в этих манифестах

**Comment by Piterden** [comment]
Ну тогда удалите это всё! Вам нужна только папка `dist`

В докер файле [опечатка](https://github.com/radio-t/pirates/blob/master/Dockerfile#L19), надо `/var/cache/apt/*`

**Comment by umputun** [comment]
нет, это не дебиан но alpine

**Comment by igoradamenko** [comment]
@umputun, как вы знаете, в репе есть тема для пиратов: https://github.com/radio-t/pirates/tree/master/hugo/themes/pirates-radio-t. При генерации сайта используются все папки и файлы, кроме папки src, там _предположительно_ лежат исходники.

_Предположительно_, потому что кажется, что это просто калька с другой темы: https://github.com/budparr/gohugo-theme-ananke (если посмотреть на её папку src, то там те же файлы). И насколько я могу судить, файлы этой темы вебпаком собирались в папку [dist](https://github.com/radio-t/pirates/tree/62cebd6dfb031825c737782689635e0b6ddddc79/hugo/themes/pirates-radio-t/static/dist), но ни app.bundle.js, ни main.css, что лежат внутри, нигде не подключаются в шаблонах. Потому вероятнее всего можно удалить папку /hugo/themes/pirates-radio-t/static/dist, а вместе с ней /hugo/themes/pirates-radio-t/src, потому что все _используемые_ стили и скрипты темы на самом деле лежат во всех остальных папках внутри /hugo/themes/pirates-radio-t/static, и никак никуда не собираются никаким вебпаком. Вероятно они остались ещё от предыдущего генератора.

Потому я предлагаю попробовать удалить и /hugo/themes/pirates-radio-t/static/dist, и /hugo/themes/pirates-radio-t/src, а затем пересобрать сайт и посмотреть, не сломается ли ничего. Скорее всего ничего не должно сломаться.

Зависимости же, о которых вы говорите, вероятно использовались авторами оригинальной темы (косвенно две из них нужны для вебпака, а одна для сборки стилей). Поскольку вам они, вероятно, не нужны, то если удаление описанных выше папок пройдёт успешно, все предупреждения пропадут :-)

**Comment by umputun** [comment]
удаление dist и src не вызвало никаких видимых проблем
